name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: unionfs-fuse-static
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo sh -c 'apt update && apt install qemu-user-static -y'
          docker pull tonistiigi/binfmt:latest
          docker run --privileged --rm tonistiigi/binfmt --uninstall qemu-*
          docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build for x86_64
        run: |
            docker run --rm -v "${{ github.workspace }}:/root" --platform=linux/amd64 ubuntu:jammy bash /root/build.sh

      - name: Build for aarch64
        run: |
            docker run --rm -v "${{ github.workspace }}:/root" --platform=linux/arm64 ubuntu:jammy bash /root/build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
